spring:
  cloud:
    gateway:
      routes:
       #Siempre respetar los espacios antes del valor
       # id: servicio-productos
      - id: servicio-productos
        #lb es load balancer. Es una ruta al microservicio, instancia con balanceo de carga
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
            #Es el numero de segmentos que esta compuesto la ruta /api/productos/**
            #En este  caso son dos palabras separadas por / y se coloca StripPrefix=2
          - StripPrefix=2
            #Colocamos el filtro personalizado por nosotros
                        #El valor de la cookie no deb tener espacio
          - EjemploCookie=Hola mi mensaje personalizado, usuario, AndresGuzman
       #Siempre respetar los espacios antes del valor
       # id: servicio-productos
      - id: servicio.items
        #lb es load balancer. Es una ruta al microservicio, instancia con balanceo de carga
        uri: lb://servicio.items
        predicates:
           - Path=/api/items/**
        filters:
            #Es el numero de segmentos que esta compuesto la ruta /api/productos/**
            #En este  caso son dos palabras separadas por / y se coloca StripPrefix=2
           - StripPrefix=2    
           #Agregamos un token a la cabecera...
           - AddRequestHeader=token-request, valordeltoken-simons-1233456
           - AddResponseHeader=token-response, valordeltoken-response-simons-123345678
           - SetResponseHeader=Content-type, text/plain
           #Pasar parametros al request (Nombre y valor separados por coma)
           - AddRequestParameter=nombre, requestParameterSaymon