spring:
  cloud:
    gateway:
      routes:
       #Siempre respetar los espacios antes del valor
       # id: servicio-productos
      - id: servicio-productos
        #lb es load balancer. Es una ruta al microservicio, instancia con balanceo de carga
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
          #En el predicado, estamos forzando a que los headers deben tener un token decimal para ir al path=/api/productos/**
          - Header=token, \d+
          - Method=GET, POST
          #En una peticion get , no enviamo ningun tipo de objeto en el request
          - Header=Content-Type, application/json
          #Enviame un paramero con el nombre color y valor verder
          #- Query=color, verde
          #Que contenga un nombre de parametro color
          - Query=color
          - Cookie=color, azul
        filters:
            #Es el numero de segmentos que esta compuesto la ruta /api/productos/**
            #En este  caso son dos palabras separadas por / y se coloca StripPrefix=2
          - StripPrefix=2
            #Colocamos el filtro personalizado por nosotros
                        #El valor de la cookie no deb tener espacio
          - EjemploCookie=Hola mi mensaje personalizado, usuario, AndresGuzman
       #Siempre respetar los espacios antes del valor
       # id: servicio-productos
      - id: servicio.items
        #lb es load balancer. Es una ruta al microservicio, instancia con balanceo de carga
        uri: lb://servicio.items
        predicates:
           - Path=/api/items/**
        filters:
            #Es el numero de segmentos que esta compuesto la ruta /api/productos/**
            #En este  caso son dos palabras separadas por / y se coloca StripPrefix=2
           - StripPrefix=2    
           #Agregamos un token a la cabecera...
           - AddRequestHeader=token-request, valordeltoken-simons-1233456
           - AddResponseHeader=token-response, valordeltoken-response-simons-123345678
           - SetResponseHeader=Content-type, text/plain
           #Pasar parametros al request (Nombre y valor separados por coma)
           - AddRequestParameter=nombre, requestParameterSaymon